version: "3"
services:
  kindle:
    image: kindle:latest
    command: wine ".wine/drive_c/Program Files (x86)/Amazon/Kindle/Kindle.exe"
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - XMODIFIERS="@im=fcitx"
      - GTK_IM_MODULE=fcitx
      - QT_IM_MODULE=fcitx
      - XIMPROGRAM=fcitx
      - LC_CTYPE=ja_JP.UTF-8
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.kindle/contents:/home/wineuser/My Kindle Content
# wine kindle
# http://nkenbou.hatenablog.com/entry/2017/04/25/125733
# https://gist.github.com/owlat7/5b63bb12a8a1237968af683fc20d3aab
